In [1]:
# Array sorting 
# Sorting along y-axis 

import numpy as np
SA1 = np.array([[4,5,2],[3,2,1]])
SA1.sort(axis =1)

print(SA1)

[[2 4 5]
 [1 2 3]]


In [2]:
# Sorting along x-axis
SA1.sort(axis=0)

In [3]:
print(SA1)

[[1 2 3]
 [2 4 5]]


In [4]:
SA3 = np.array([[9,8],[12,7]])
SA3.sort(axis=0)
SA3

array([[ 9,  7],
       [12,  8]])