In [1]:
# Creating NumPy Arrays
import numpy as np
A1_1D = np.array([11,13,15,17,19])                         # One dimensional array
A2_2D = np.array([[11,12,13,14],[34,35,36,37]])              # Two dimensional array
print(A1_1D)
print(A2_2D)

[11 13 15 17 19]
[[11 12 13 14]
 [34 35 36 37]]


In [2]:
# Find the shape of an array
print(A1_1D.shape)
print(A2_2D.shape)

(5,)
(2, 4)


In [3]:
# Number of Dimensions
print(A1_1D.ndim)
print(A2_2D.ndim)

1
2


In [4]:
# Creating a NumPy array using 'arange' function

AA = np.arange(5)
print(AA)

[0 1 2 3 4]


In [5]:
AAR = np.arange(2,20,4) #(start,end,step)
print(AAR)

[ 2  6 10 14 18]


In [6]:
# Creating NumPy array using linspace funciton
# generate linear evenly spaced elements between the start and end

AL = np.linspace(0,5,4)
print("linspace funciton \n",AL)

linspace funciton 
 [0.         1.66666667 3.33333333 5.        ]


In [7]:
# NumPy array creation using various funciton 
# NumPy.zeros

print("array funciton with zeros using numpy.zeros function \n", np.zeros((5,8)))

array funciton with zeros using numpy.zeros function 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
# NumPy.ones

print("array funciton with ones using numpy.ones function \n", np.zeros((2,3)))

array funciton with ones using numpy.ones function 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# NumPy.eye

print("identify matrix using numpy.eye function \n", np.eye(3))

identify matrix using numpy.eye function 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# NumPy.diag

print("Diagonal array using numpy.diag function \n", np.diag((1,2,3,4)))

Diagonal array using numpy.diag function 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [11]:
# NumPy.randon.rand
# using the rand, randn funcitons
# Rand(m) produces uniformly distributed random numbers with range 0 to m

np.random.seed(20)  #set seed
ARR = np.random.rand(4)
print("ND array using the random funtion ", ARR)

ND array using the random funtion  [0.5881308  0.89771373 0.89153073 0.81583748]


In [12]:
# Rand(m) produces a normally distributed ( Gaussian ) random numbers

ARG = np.random.randn(6)
print("randn(m) funtion array \n" , ARG)

randn(m) funtion array 
 [ 0.35753652 -2.34326191 -1.08483259  0.55969629  0.93946935 -0.97848104]


In [13]:
# Numpy.Empty
# Creating uninitialized array

print("Empty matrix using numpy.empty function \n", np.empty((2,3)))

Empty matrix using numpy.empty function 
 [[0.35753652 2.34326191 1.08483259]
 [0.55969629 0.93946935 0.97848104]]


In [14]:
# NumPy.tile
# Allows one to construct an array from a smaller array by repeating it serval times
A11 = np.array([[5,6],[1,3]])
print(A11)

AT = np.tile(A11,3)
print(AT)

[[5 6]
 [1 3]]
[[5 6 5 6 5 6]
 [1 3 1 3 1 3]]
