In [1]:
# Array indices in NumPy start at 0
import numpy as np

A12 = np.arange(10)
#print entire array
A12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
print(A12[0])   # Print 1st element
print(A12[1])   # Print 2nd element
print(A12[-1])   # Print last element

0
1
9


In [3]:
# Arrays can be reversed using the ::-1 idiom
A12[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [4]:
# Multi-dimensional arrays are indexed using tuples of integers

A13 = np.array([[1,2,3],[4,5,6],[7,8,9]])
A13

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Access the elements of second row and first column
A13[2,1]

8

In [6]:
# Modify value at A12[2,1]
A13[2,1] = 21
A13

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 21,  9]])

In [7]:
# Retrive row 1
print(A13[1])
print(A13[1,:])

[4 5 6]
[4 5 6]


In [8]:
# Retrive second row and all columns
A13[2,:]

array([ 7, 21,  9])

In [9]:
# Retrive second column
A13[:,2]

array([3, 6, 9])

In [10]:
## Array slicing 

## Syntak : [StartIndex : EndIndex : StepValue]

A14 = 2*np.arange(12)

In [11]:
print(A14)
# Get 5 elements starting from index 0 to index 5 stopped by 2
A14[0:6:2]

[ 0  2  4  6  8 10 12 14 16 18 20 22]


array([0, 4, 8])

In [12]:
# What happens if add step index as :
A14[:::]

SyntaxError: invalid syntax (<ipython-input-12-b1bad8343e26>, line 6)

In [13]:
# If we wish to include an EndIndex value
A14[0::2]

array([ 0,  4,  8, 12, 16, 20])

In [14]:
# Without step value from 0 Index to end Index
A14[::]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [15]:
## Assignment and slicing can be combined

A16 = np.array([1,2,3,4,6,8,9,0,1,2,3])
print(A16)

# Replaces all elements starting from index 0 to index 3 
A16[:3] = 1
print(A16)

[1 2 3 4 6 8 9 0 1 2 3]
[1 1 1 4 6 8 9 0 1 2 3]


In [16]:
# Replaces all elements starting from index 4 to last

A16[4:] = np.ones(7)
print(A16)

[1 1 1 4 1 1 1 1 1 1 1]


In [17]:
# Creating an 5X5 array
A17 = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])
A17

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
# Same can be created using 'ARANGE' function

A18 = np.arange(0,25).reshape(5,5)
print(A18)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [19]:
A17[0,2:4]

array([2, 3])

In [20]:
A17[3:,4:]

array([[19],
       [24]])

In [21]:
A18[:,2]  # All rows of column 2 

array([ 2,  7, 12, 17, 22])

In [22]:
A17[2::2,::2]   # start at row 2, till last  and step 2 , # start at index 0 till last , step 2 

array([[10, 12, 14],
       [20, 22, 24]])