In [1]:
# Array masking  # To filter 
import numpy as np
np.random.seed(20)
A20 = np.random.randint(25,50,10)
print(A20)

[28 40 34 45 36 47 32 27 25 47]


In [2]:
# Boolean mask array to filter out even numbers
A20_Even = (A20 % 2 == 0)
A20_Even

array([ True,  True,  True, False,  True, False,  True, False, False,
       False])

In [3]:
# get exact even numbers instaed of true or false
A20_Num = A20[A20_Even]
A20_Num

array([28, 40, 34, 36, 32])

In [4]:
## Masking to eliminate missing values 

AC = np.array(['India','Austrila','Srilanka','Bangladesh',''])
AC

array(['India', 'Austrila', 'Srilanka', 'Bangladesh', ''], dtype='<U10')

In [5]:
AC[AC =='']='Iran'
AC

array(['India', 'Austrila', 'Srilanka', 'Bangladesh', 'Iran'],
      dtype='<U10')

In [6]:
A21 = 20*np.arange(11,20)
A21

array([220, 240, 260, 280, 300, 320, 340, 360, 380])

In [7]:
A21[[1,3,6]] # To create an smaller array from the A21 array using indices
# If you use single braces , it will throw an error.

array([240, 280, 340])

In [8]:
## Assignment with Indexing

A21[[1,3]] = 65
A21

array([220,  65, 260,  65, 300, 320, 340, 360, 380])