In [1]:
import numpy as np
C1 = np.arange(5)
C1

array([0, 1, 2, 3, 4])

In [2]:
C2 = C1[::2]   # Copy of the values from array C to array C1 from 0 to last by step 2 
C2

array([0, 2, 4])

In [3]:
C2[1] = -4

In [4]:
print(C2)  # When replaced the value of 1 with -4 in C2 also reflected in C1 , where we have not changed , as C2 is view of C1
print(C1)

[ 0 -4  4]
[ 0  1 -4  3  4]


In [5]:
# Modifying the veiw , it's base value also modified as shown above.

In [6]:
# If you widh you modify the subarray but it shoulod not modify the base array , then we use COPY instead of view
C3 = np.arange(10)
print(C3)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
C4 = C3[:7].copy()
print(C4)

[0 1 2 3 4 5 6]


In [8]:
C4[3] = 10
print(C4)

[ 0  1  2 10  4  5  6]


In [9]:
print(C3)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# See the above output of C3 and C4, the base array hasn't modified when we done copy
# original array remains unaffected when the copied array is modified. 