In [1]:
## Basic Arithmetic Operations
    # Sum
    # product
    # Substract
    # Division

In [2]:
import numpy as np
O = np.arange(1,4)*4
print(O)

[ 4  8 12]


In [3]:
O1 = np.arange(1,10)**4
print(O1)

[   1   16   81  256  625 1296 2401 4096 6561]


In [4]:
O2 = O ** 0.5
print(O2)

[2.         2.82842712 3.46410162]


In [5]:
# Operations also work element-wise array is the second operand
S1 = 3+np.arange(1,20,2)
print(S1)

[ 4  6  8 10 12 14 16 18 20 22]


In [6]:
S2 = np.arange(1,11)
print(S2)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
S3 = S2 - S1   # Shape must be equal
print(S3)# Division

[ -3  -4  -5  -6  -7  -8  -9 -10 -11 -12]


In [9]:
# Division
D = S1/S2
print(D)

[4.         3.         2.66666667 2.5        2.4        2.33333333
 2.28571429 2.25       2.22222222 2.2       ]


In [10]:
# Multiplication 
M = S1*S2
print(M)

[  4  12  24  40  60  84 112 144 180 220]


In [11]:
# We use timie fucntion,to know how time works with numpy package ( how much time it takes for operations)
T = np.arange(100)
%timeit T**4

2.28 µs ± 320 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
 TR = range(100)
%timeit [TR[i]**4 for i in TR]

94.3 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [13]:
# Matrix Multiplication

# Matrix Multiplication is not same as array multiplicaiton ; array multiplication done element wise but in Matrix it is different.

M1 = np.array([[5,5],[7,7]])
print("Matix M1 is \n",M1)
M2 = np.array([[7,7],[5,5]])
print("Matix M2 is \n",M2)

M3 = M1.dot(M2)
print("Multiplication of Matrix M1 and M2 is \n",M3)

Matix M1 is 
 [[5 5]
 [7 7]]
Matix M2 is 
 [[7 7]
 [5 5]]
Multiplication of Matrix M1 and M2 is 
 [[60 60]
 [84 84]]


In [14]:
## Comparisons and logical operations 
## Comparisons and logical operations are also element-wise

CL1 = np.arange(2,7)
CL2 = np.arange(10,5,-1)
CL3 = CL1 < CL2
print(CL3)

[ True  True  True  True False]


In [15]:
LA1  = np.array([False,True,False,False,True])
LA2  = np.array([True,False,False,False,True])
LA3  = np.logical_and(LA1,LA2)
LA3

array([False, False, False, False,  True])

In [16]:
LA4  = np.logical_or(LA1,LA2)
print(LA4)

[ True  True False False  True]


In [17]:
# the below operations as well element-wise
    # log
    # sin
    # cos
    # exp

In [18]:
S1 = np.array([np.pi,np.pi/2])
S2 = np.sin(S1)
print(S2)

[1.2246468e-16 1.0000000e+00]


In [19]:
# Element-wise operations , two arrays must have same shape , or else it throws an error. 

T1 = np.array([[1,2,3],[4,5,6]])
T2 = T1.T 

print(T1)
print(T2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
T1 = np.array([[1,2,3],[4,5,6]])
T2 = np.transpose(T1)

print(T1)
print(T2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [21]:
# Compare arrays , not in element-wise , but array wise

CA1 = np.arange(1,7)
CA2 = np.array([1,2,3,4,5,6])

CA3 = np.array_equal(CA1,CA2)

print(CA3)

True


In [22]:
# Equivalent to the above expression

CA4 = np.all(CA1 == CA2)
print(CA4)

True
