In [1]:
## Reduction 
# np.sum and np.prod perform reduces an array

import numpy as np

R1 = np.arange(1,6)
R1.prod()

120

In [2]:
R1.sum()

15

In [3]:
## In Multi-dimensional array, use axis parameter to perform ( reduces ) row-wise/column-wise

R2 = np.array([np.arange(1,6),np.arange(1,6)])
print(R2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [4]:
CW = np.prod(R2,axis=0)    # Column-wise reduction
RW = np.prod(R2,axis=1)    # Row-wise reduction

print(CW,RW)

[ 1  4  9 16 25] [120 120]


In [5]:
# When we don't specify the axis

NA = np.prod(R2)  # it gives the product of all numbers in array
print(NA)

14400


In [6]:
print(R2.sum())
print(R2.mean())

30
3.0


In [7]:
## Statistical Operations

# std() , mean() , median() , cumsum()

np.random.seed(20)
SS1 = np.random.randint(0,10, size=(5,4))
print(SS1)

[[3 9 4 6]
 [7 2 0 6]
 [8 5 3 0]
 [6 6 0 9]
 [5 7 5 2]]


In [8]:
SS1.mean()

4.65

In [9]:
SS1.std()

2.7617928959282954

In [10]:
print(SS1.var(axis=0))
print(SS1.var(axis=1))

[ 2.96  5.36  4.24 10.24]
[ 5.25    8.1875  8.5    10.6875  3.1875]


In [11]:
SS1.cumsum()

array([ 3, 12, 16, 22, 29, 31, 31, 37, 45, 50, 53, 53, 59, 65, 65, 74, 79,
       86, 91, 93], dtype=int32)

In [12]:
## Logical operations

#np.all() -::- This is used for element-wise and all of the elements
#np.any() -::- This is used for element-wise or all of the elements
np.random.seed(20)
L1 = np.random.randint(11,20,size=(4,5))
print(L1)

[[14 15 17 18 13]
 [11 17 19 16 14]
 [11 17 17 11 16]
 [18 16 13 17 14]]


In [13]:
L2 = np.any((L1%7)==0) #This condition should be satisfied with any element(s) in array
print(L2)

True


In [14]:
L2 = np.all((L1%7)==0) #This condition should be satisfied with all elements in array
print(L2)

False
