## Broad Casting 

In [1]:
# Here we make use of arrays that exactly have no same shape
import numpy as np

A1 = np.ones([5,4])   # 5 rows and 4 colums
print(A1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
A2 = np.array([5,2,2,1])  # 1 row and 4 columns
print(A2)

[5 2 2 1]


In [3]:
## A2 is broadcasted to A1

A3 = A2+A1
print(A3)

[[6. 3. 3. 2.]
 [6. 3. 3. 2.]
 [6. 3. 3. 2.]
 [6. 3. 3. 2.]
 [6. 3. 3. 2.]]


In [4]:
# Here [5,2,2,1] is added to all rows in the A1 in element-wise ( 1+5,1+2,1+2,1+1)

# What if we have 1D array broadcast

A4 = np.array([[11,12,13]])
A5 = A4.T
print(A4,"\n",A5)

[[11 12 13]] 
 [[11]
 [12]
 [13]]


In [5]:
# Both row and col are broadcasted and we end up with a 3X3 array
A6 = A4+A5
print(A6)

[[22 23 24]
 [23 24 25]
 [24 25 26]]
