In [1]:
# Flattening a multi-dimensional array
# np.ravel() - flatten a multi-dimensional array

import numpy as np

F1 = np.array([np.arange(2,7),np.arange(15,20)])
print(F1)

[[ 2  3  4  5  6]
 [15 16 17 18 19]]


In [2]:
F2 = F1.ravel()
print(F2)

[ 2  3  4  5  6 15 16 17 18 19]


In [3]:
F1.T

array([[ 2, 15],
       [ 3, 16],
       [ 4, 17],
       [ 5, 18],
       [ 6, 19]])

In [4]:
F3 = F1.T.ravel()
print(F3)
# We use ravel function to convert a multi-dimensioanl array into single dimension array

[ 2 15  3 16  4 17  5 18  6 19]
