In [1]:
# We use complex indexing to assign values from a smaller array to a larger array 

import numpy as np

AR1 = np.arange(20)
AR1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [2]:
AR1I = np.arange(-11,-20,-1)[::-1]
AR1I

array([-19, -18, -17, -16, -15, -14, -13, -12, -11])

In [3]:
# Slice out the first 6 elements of AR1 and replace with elements from AR1I

AR1[:9] = AR1I

In [4]:
AR1

array([-19, -18, -17, -16, -15, -14, -13, -12, -11,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])