In [1]:
# Importing Numpy library
import numpy as np

In [2]:
# Numpy version and configuration
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SatishMoparthi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/SatishMoparthi/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SatishMoparthi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_librarie

In [3]:
# Create a null vector of size 10
NV = np.zeros(10)
print(NV)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Create a null vector of size 10 but fifth value is 1
NV = np.zeros(10)
NV[4]=1
print(NV)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
# Vector with values from 10 - 50
V = np.arange(10,50)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#Reverse a vector 
v = V[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [7]:
# Create 3X3 matrix
M = np.arange(9).reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#Find indices of non-zero elements from a array
INZ = np.nonzero([1,2,0,0,3,4,0,3])
print(INZ)

(array([0, 1, 4, 5, 7], dtype=int64),)


In [9]:
#3X3 identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 3X3X3 matrix with random values
RV = np.random.random((3,3,3))
print(RV)

[[[0.62112365 0.59462526 0.25909015]
  [0.02134596 0.32712454 0.23174708]
  [0.686389   0.532283   0.29694285]]

 [[0.7310428  0.21164191 0.54436566]
  [0.25398386 0.53631884 0.24221377]
  [0.80176417 0.31693512 0.03358851]]

 [[0.84067897 0.59785114 0.14719428]
  [0.73768411 0.20531683 0.12913229]
  [0.21382213 0.62407539 0.9452563 ]]]


In [11]:
#Create a 10X10 array with random values and find the mean , min and max
MMM = np.random.random((10,10))
MMMmin, MMMmax = MMM.min(),MMM.max()
print(MMMmin,MMMmax)

0.013557482544483523 0.9956625183099512


In [12]:
#Random vector of size 30 and find mean 
RVM = np.random.random(30)
m = RVM.mean()
print(m)

0.485557837111151


In [13]:
#Create 2d array with 1 on the border and Zero in the middle

TA = np.ones((10,10))
TA[1:-1,1:-1] = 0
print(TA)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


In [15]:
#Create 5X5 matrix with values 1,2,3,4 just below the diagonal
D = np.diag(1+np.arange(4),k=-1) # for above diagonal +1 and remove k = +-1 in diagonal
print(D)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
#8X8 matrix and fill it with checkbroad pattern
C = np.zeros((8,8),dtype=int)
C[1::2,::2] = 1
C[::2,1::2] = 1
print(C)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
#Consider the (2,3,4) shape array and what the index (x,y,z) of the 10th element.
print(np.unravel_index(10,(2,3,4)))

(0, 2, 2)


In [18]:
#Create a check broad 8X8 matrix using the tile fucntion
T = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(T)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
#Normalize a 5X5 random matrix
RM = np.random.random((5,5))
RMmin,RMmax = RM.min(),RM.max()
RM = (RM - RMmin)/(RMmax-RMmin)
print(RM)

[[0.17985894 0.99915848 0.34007547 0.39694154 0.79532039]
 [0.48570381 0.35638881 0.82072486 0.56505025 0.43243917]
 [0.63990238 1.         0.90569858 0.18826041 0.        ]
 [0.52801103 0.62441807 0.59425676 0.62522429 0.8792278 ]
 [0.73109476 0.07667226 0.33114422 0.34829617 0.33648495]]


In [20]:
#Create a custom dtype that describes a color as four unisgned bytes
C = np.dtype([("r",np.ubyte,1),
              ("g",np.ubyte,1),
              ("b",np.ubyte,1),
              ("a",np.ubyte,1)])
print(C)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\SatishMoparthi\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


In [21]:
#Multiply 5X3 matrix by 3X2 matrix
Mul = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Mul)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [22]:
#Negate all elements which are between 3 and 8 , in a given 1D array
N = np.arange(11)
N[(3<N)&(N<=8)] *= -1
print(N)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [23]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [24]:
import numpy as np

print(np.array(0))
print(np.array(0.))

0
0.0


In [25]:
# Extract the integer part of an random array using 5 differnet methods

Z = np.random.uniform(0,10,10)
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[5. 8. 6. 8. 2. 5. 8. 4. 3. 1.]
[5. 8. 6. 8. 2. 5. 8. 4. 3. 1.]
[5. 8. 6. 8. 2. 5. 8. 4. 3. 1.]
[5 8 6 8 2 5 8 4 3 1]
[5. 8. 6. 8. 2. 5. 8. 4. 3. 1.]


In [26]:
print(Z)

[5.85680403 8.85494317 6.33124925 8.71058101 2.0462094  5.90679685
 8.70380569 4.61067842 3.12401747 1.88855214]


In [27]:
# Create a 5X5 matrix with row values ranging from 0 to 4

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [28]:
#Consider a generator function that generates 10 integers and use it to built an array

def generate():
    for x in range(10):
        yield x
Z  = np.fromiter(generate(),dtype=float,count=1)
print(Z)

[0.]


In [29]:
#make a array immutable ( read-only)

M = np.zeros(10)
M.flags.writeable = False
M[0] = 1
#print(M)

ValueError: assignment destination is read-only

In [30]:
# Consider a random 10X2 matrix representing cartesian coordinates , convert them into polar co-ordinates

Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.78101793 0.25118    0.16256501 0.36401711 1.22052769 0.68824334
 0.41192096 1.06166578 0.70077469 0.21114577]
[0.04809839 0.91974239 1.42843919 0.51798485 0.94894919 1.41204804
 0.90063604 0.49930973 0.80406236 0.48081592]


In [31]:
# Create random vector of size 10 and replace the maximum value by 0

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.14034472 0.86131221 0.60926012 0.42129569 0.2195652  0.83201002
 0.50254919 0.84710252 0.         0.43327126]


In [32]:
# Create a structured array with X and Y coordinates covering the [0,1]X[0,1] area

Z = np.zeros((10,10),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888