In [1]:
# Reshape returns a view keeping the underlying array unchanged

import numpy as np
R1 = np.arange(11,26)
R2 = R1.reshape(3,5)
print(R1)
print(R2)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
