In [1]:
# numpy.ndarray.resize

import numpy as np

RE1 = np.arange(10,15)
RE1.resize((8,))
print(RE1)

[10 11 12 13 14  0  0  0]


In [2]:
# It doesn't allow to resize if there are any other referrences. 

RE2 = np.arange(10,15)
RE3 = RE2
RE3.resize((8,))
print(RE3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [3]:
# It doesn't allow to resize if there are any other referrences. 

RE2 = np.arange(10,15)
RE3 = RE2
RE3.resize((5,))
print(RE3)

[10 11 12 13 14]


In [4]:
# Use the numpy.resize function instead of resize funtion to change underlying array as well.

RE5 = np.resize(RE2,(8,))
print(RE5)

[10 11 12 13 14 10 11 12]
